# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:16.8.0

pipelines:
  branches:
    uat:
      - step:
          name: "Build"
          size: 2x
          script:
            # - nvm install 16.8
            - apt-get update
            - apt-get install -y zip unzip
            - npm install
            - npm run build-uat
            - cd build
            - zip -r ../elcss.4s.serviceuserportal-$BITBUCKET_BUILD_NUMBER.zip .
          artifacts: 
            - elcss.4s.serviceuserportal-*.zip
      - step:
          name: "Deploy to Azure"
          deployment: Uat
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.1
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: 'elcss.4s.serviceuserportal-$BITBUCKET_BUILD_NUMBER.zip'
  

    master:
      - step:
          name: "Build"
          size: 2x
          script:
            # - nvm install 16.8
            - apt-get update
            - apt-get install -y zip unzip
            - npm install
            - npm run build
            - cd build
            - zip -r ../elcss.4s.serviceuserportal-$BITBUCKET_BUILD_NUMBER.zip .
          artifacts: 
            - elcss.4s.serviceuserportal-*.zip
      - step:
          name: "Deploy to Azure"
          deployment: Production
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.1
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: 'elcss.4s.serviceuserportal-$BITBUCKET_BUILD_NUMBER.zip'