const Map<String, String> zh_CH = {
  'home_search_key': '品名/代码',
  'my': '我的',
  'login': '用户登录',
  'unknown': '未知',
  'visitor': '游客',
  'login_out': '退出登录',
  'theme': '皮肤设置',
  'language': '语言设置',
  'chinese': '中文',
  'english': '英文',
  'log off': '确定退出',
  'avatar': '头像',
  'upload': '上传',
  'save': '保存',
  'cancel': '取消',
  'feedback': '疑惑解答',
  'vip': '升级VIP',
  'description': '描述',
  'histroy': '历史疑惑',
  'submit': '提交',
};
