const Map<String, String> zh_HK = {
  'home_search_key': '品名/代碼',
  'my': '我的',
  'login': '用戶登錄',
  'unknown': '未知',
  'visitor': '遊客',
  'login_out': '退出登錄',
  'theme': '皮膚設置',
  'language': '語言設置',
  'chinese': '中文',
  'english': '英文',
  'log off': '確定退出',
  'avatar': '頭像',
  'upload': '上傳',
  'save': '保存',
  'cancel': '取消',
  'feedback': '疑惑解答',
  'vip': '升級VIP',
  'description': '描述',
  'histroy': '歷史記錄',
  'submit': '提交',
};
